# Build stage
FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o webanalyzer ./cmd/api/main.go

# Final stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/webanalyzer .
COPY .env .
EXPOSE 8080
CMD ["./webanalyzer"]